version: 2
jobs:
  build:
    working_directory: ~/renalwarev2
    docker:
      # this is important to use proper image with browsers support
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: renalware
          RAILS_ENV: test
      # We use a custom docker image uploaded to DockerHub - see the Dockerfile in this folder.
      # Note it is important to disable spring otherwise it affects the simplecov output because
      # spring loads files ahead of time - for example using spring you might find app/helpers
      # are not included in the coverage.
      # - image: airslie/renalware-circleci-primary:0.0.5
      #   environment:
      #     - RAILS_ENV: test
      #     - RACK_ENV: test
      #     - DISABLE_SPRING: 1
      - image: circleci/postgres:10.3-alpine
        environment:
          #   POSTGRES_DB: project-name_test
          #   POSTGRES_PASSWORD: ""
          POSTGRES_USER: renalware
      - image: redis:3.2.7

    parallelism: 1

    steps:
      - checkout

      # Also pull the UKRDC XSDs
      - run: git submodule sync ; git submodule update --init

      - run: mkdir -p ./tmp/test-artifacts
      - run: mkdir -p ./coverage

      # Restore bundle cache
      - type: cache-restore
        key: renalwarev2-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle --jobs=3 --retry=3

      # Store bundle cache
      - type: cache-save
        key: renalwarev2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - run: sudo sh -c 'wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -'
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-10

      # https://codegists.com/code/circleci-2.0-configuration/
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter

      - run: sudo apt install postgresql-client-10 pandoc unzip unrar-free

      # Database set-up
      - run: cp ./spec/dummy/config/database.circle.yml ./spec/dummy/config/database.yml
      - run: RAILS_ENV=test bundle exec rake app:db:create
      - run: RAILS_ENV=test bundle exec rake app:db:structure:load

      # Check gems for security vulnerabilities in gems
      - run: bundle exec bundle-audit update && bundle exec bundle-audit check

      - run:
          name: Notify Code Climate of a pending report
          command: |
            ./cc-test-reporter before-build

      # RSpec
      - type: shell
        command: |
          case $CIRCLE_NODE_INDEX in 0) bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            --fail-fast ;; esac
          # $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Cucumber domain features
      - type: shell
        command: |
          case $CIRCLE_NODE_INDEX in 0) bundle exec cucumber --format progress \
                               --format junit \
                               --out /tmp/test-results/cucumber-domain.xml ;; esac
          # $(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)

      # Cucumber web features
      - type: shell
        command: |
          case $CIRCLE_NODE_INDEX in 0) TEST_DEPTH=web bundle exec cucumber \
                               -p rake_web \
                               --format progress \
                               --format junit \
                               --out /tmp/test-results/cucumber-web.xml ;; esac
          # $(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)

      # Save artifacts ie coverage data
      - store_artifacts:
          path: ./tmp/test-artifacts
          destination: build

      # Upload test results (junit xml)
      - store_test_results:
          path: /tmp/test-results

      - run:
          name: Report code coverage to Code Climate
          command: |
            ./cc-test-reporter after-build -t simplecov --exit-code $? || true

      # Test seeding
      - run: case $CIRCLE_NODE_INDEX in 0) pushd ./spec/dummy ; bundle exec rails db:environment:set RAILS_ENV=test ; popd ;; esac
      - run: case $CIRCLE_NODE_INDEX in 0) bundle exec rake app:db:migrate:reset app:db:seed RAILS_ENV=test ;; esac
