super_admin:
  - Renalware::Role
  - Renalware::Hospitals::Ward
  - Renalware::HD::Dialysate
  - Renalware::HD::Dialyser
  - Renalware::HD::CannulationType
admin:
  - Renalware::User
  - Renalware::BagType
  - Renalware::Drugs::Drug
  - Renalware::Drugs::Type
  - Renalware::EdtaCode
  - Renalware::Events::Type
  - Renalware::MedicationRoute
  - Renalware::Modality::Description
  - Renalware::OrganismCode
  - Renalware::PRDDescription
  - Renalware::Hospitals::Unit
  - Renalware::HD::Station
