shared: &shared
  host: <%= ENV.fetch("LDAP_HOST", "localhost") %>
  port: <%= ENV.fetch("LDAP_PORT", 389) %>
  # Admin user to bind as, to perform searches
  admin_password: <%= ENV.fetch("LDAP_ADMIN_PASSWORD") %>
  admin_user: <%= ENV.fetch("LDAP_ADMIN_USER", "cn=admin,dc=renalware,dc=app") %>
  base: <%= ENV.fetch("LDAP_BASE", "dc=renalware,dc=app") %>
  attribute: <%= ENV.fetch("LDAP_USERNAME_ATTRIBUTE", "uid") %> # eg "smithj"

development:
  ssl: false
  <<: *shared

test:
  ssl: simple_tls
  <<: *shared

uat:
  ssl: true
  <<: *shared

production:
  ssl: true
  <<: *shared
