// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userGuideSidebar: [{type: 'autogenerated', dirName: 'user-guide'}],
  technicalSidebar: [{type: 'autogenerated', dirName: 'technical'}],
};

export default sidebars;
